### ISSUE TITLE
Increase radiation resistance of mining hardsuits

### ISSUE THREAD

**Issue by Jonathan-Fort** [Jonathan-Fort/YWPolarisVore#17]
#### Brief overview of the feature
Mining hardsuits should have higher radiation resistance to deal with the fact that they are industrial suits intended to be used in hazardous environments.

#### What you want to happen
Radiation resistance of mining hardsuits should increase alongside the engineering hardsuits, or a means of upgrading them should be made available.

**Comment by Jonathan-Fort** [comment]
Resolved in 1.0

**Comment by Jonathan-Fort** [comment]
@Dwaggy mining hardsuits now have 85% radiation resistance. Do you feel this is acceptable?

**Comment by Dwaggy** [comment]
> 
> 
> @Dwaggy mining hardsuits now have 85% radiation resistance. Do you feel this is acceptable?

It sounds high, But given that the default kills them outright. it might be enough, the idea is to still punish the miner for been out in the storms and breaking the artifacts, without..you know.. killing them or making them drop in crit. 
So 85% should be good? hard to tell without testing it to be sure of what damage is done.
